---
title: Your awesome title
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/flips-slides-site"
url: http://techmex-io.github.io/flips-slides-site
github_username: jekyll
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
timezone: Etc/UTC
